
from settings.representation_settings.menu_representation_settings import MenuReprSettings
from settings.representation_settings.records_representation_settings import RecordReprSettings, RecordsBookReprSettings
from settings.representation_settings.notes_representation_settings import NotesReprSettings, NotesBookReprSettings
